<li class="J-has-share listNews-item-s1 clearfix">
    <div class="img fl"><a href="[field:arcurl/]" target="_blank"><img class="animation" src="[field:litpic/]" alt="[field:litpic/]" width="180" height="135"></a></div>
    <div class="info">
      <h3><a class="J-share-a" href="[field:arcurl/]" target="_blank">[field:title/]</a></h3>
      <p class="desc"><!--来源：[field:source/]-->　[field:description/]...</p>
      <p class="from">[field:pubdate function="GetDateTimeMK(@me)"/] 来源：[field:source/]</p>
     <!-- <div class="J-bdsharebuttonbox-wrap">
        <div class="J-bdsharebuttonbox bdsharebuttonbox clearfix"><span class="fl">分享</span><a class="J-bdshare bds-tsina fl" data-cmd="tsina" href="javascript:;"></a><a class="J-bdshare bds-qzone fl" data-cmd="qzone" href="javascript:;"></a><a class="J-bdshare bds-tqq fl" data-cmd="tqq" href="javascript:;"></a><a class="J-bdshare bds-weixin fl" data-cmd="weixin" href="javascript:;"></a></div>
      </div>-->
      
    </div>
  </li>