<li class="J-has-share listNews-item-s1 clearfix">
                <div class="img fl"><a href="[field:arcurl/]" target="_blank"> <img class="animation" src="[field:litpic/]"   alt="[field:title/]" width="180" height="135"></a> </div>
                <div class="info">
                      <h3> <a class="J-share-a" href="[field:arcurl/]" target="_blank">[field:title/]</a> </h3>
                      <p class="desc" style="height: 60px; overflow: hidden;">　　[field:info/]......</p>
                      <p class="from">[field:pubdate function=MyDate('m-d',@me)/]    来源：[field:source/]</p>
                      <div class="J-bdsharebuttonbox-wrap">
                    <div class="J-bdsharebuttonbox bdsharebuttonbox clearfix bdshare-button-style0-16" data-bd-bind="1453858492231"> <span class="fl">分享</span><a class="J-bdshare bds-tsina fl" data-cmd="tsina" href="javascript:;" title="分享到新浪微博"></a> <a class="J-bdshare bds-qzone fl" data-cmd="qzone"  href="javascript:;" title="分享到QQ空间"></a> <a  class="J-bdshare bds-tqq fl" data-cmd="tqq" href="javascript:;" title="分享到腾讯微博"></a> <a class="J-bdshare bds-weixin fl" data-cmd="weixin"  href="javascript:;" title="分享到微信"></a> </div>
                  </div>
                    </div>
              </li>