<li><a title="[field:title/]"
                                     href="[field:arcurl/]"
                                     target="_blank" class="news_pic"><img class="animation"
                                          src="[field:litpic/]"
                                          alt="[field:title/]" width="145" height="105"></a><a
                                      href="[field:arcurl/]"
                                      target="_blank" class="title_news" title="[field:title/]">[field:title/]</a></li>