<li class="special-item"> <a class="clearfix " href="[field:arcurl/]" title="[field:title/]" target="_blank"> <span class="index i[field:global name=autoindex runphp="yes"]@me=@me;[/field:global] "></span>
                    <p class="fl img"><img src="[field:litpic/]" width="100" height="75" alt="[field:title/]"></p>
                    <p class="txt">[field:title/]</p>
                    </a> </li>