<?php
$z[0]=Array("global","",164,191);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("channel","\r\n          <li><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></li>       ",236,369);
$z[1][4]['type']="top";
$z[2]=Array("global","",811,838);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("global","",998,1025);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",1192,1224);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1542,1574);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1611,1637);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("field","",1645,1667);
$z[7][4]['name']="typename";
$z[8]=Array("global","",1707,1734);
$z[8][4]['name']="cfg_indexurl";
$z[9]=Array("global","",1736,1762);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("field","",1798,1820);
$z[10][4]['name']="typename";
$z[11]=Array("global","",1956,1981);
$z[11][4]['name']="cfg_cmsurl";

?>