<?php
$z[0]=Array("global","",428,460);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",519,551);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",599,631);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",838,870);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",975,1007);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("channel","\r\n            <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n            	",1282,1494);
$z[5][4]['type']="son";
$z[5][4]['row']="4";
$z[5][4]['typeid']="19";
$z[5][4]['currentstyle']="<a class='active first' href='javascript:;'>~typename~</a>";
$z[6]=Array("type","[field:typename/]",1698,1750);
$z[6][4]['typeid']="20";
$z[7]=Array("field","",1845,1866);
$z[7][4]['name']="content";
$z[8]=Array("include","",2038,2081);
$z[8][4]['filename']="style_footer.htm";
$z[9]=Array("global","",2118,2150);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",2883,2915);
$z[10][4]['name']="cfg_templets_skin";

?>